from typing import Protocol
from pandas import DataFrame
import numpy as np

from src.commands.command_utils import ProjectType
from src.shell_project import ShellProject
from src.commands.command_utils import MlModel
from src.MLOps.utils.base import BaseEstimator



class Model(Protocol):
    projects: dict[str, ShellProject]
    current_project: ...
    def create(self, alias: str, type: ProjectType) -> str: ...

    def delete(self, alias: str) -> str: ...

    def list_projects(self) -> str: ...

    def set_current_project(self, alias: str) -> str: ...

    def pcp(self) -> str: ...

    def add_data(self, df_name: str) -> str: ...

    def read_data(self, head: int = 5) -> DataFrame: ...

    def make_X_y(self, target: str) -> str: ...

    def clean_data(self) -> str: ...

    def log_model(self, model_name: "MlModel", predictions: np.ndarray, params: dict[str, float | int | str], **kwargs) -> str: ...

    def summary(self) -> str: ...

    def log_predictions_from_best(self, *models: BaseEstimator, **kwargs) -> str: ...